## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

## Bitnami NGINX image version
## ref: https://hub.docker.com/r/bitnami/nginx/tags/
##
image:
  registry: 679196758854.dkr.ecr.us-west-1.amazonaws.com
  repository: bitnami-nginx
  tag: 1.16.1-debian-10-r0
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## String to partially override nginx.fullname template (will maintain the release name)
##
nameOverride: nginx-testing

## String to fully override nginx.fullname template
##
fullnameOverride: nginx-testing

## Custom server block to be added to NGINX configuration
## PHP-FPM example server block:
## serverBlock: |-
##   server {
##     listen 0.0.0.0:8080;
##     root /app;
##     location / {
##       index index.html index.php;
##     }
##     location ~ \.php$ {
##       fastcgi_pass phpfpm-server:9000;
##       fastcgi_index index.php;
##       include fastcgi.conf;
##     }
##   }
##
# serverBlock:

## Number of replicas to deploy
##
replicaCount: 1

## Pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations:
  rafay.dev/registry-rx28oml: veer-ecr
  rafay.dev/logging: regression-es-ep

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node labels for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: {}

## NGINX containers' resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits: {}
  #   cpu: 100m
  #   memory: 128Mi
  requests: {}
  #   cpu: 100m
  #   memory: 128Mi

## NGINX containers' liveness and readiness probes
## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
##
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  timeoutSeconds: 3
  periodSeconds: 5

## NGINX Service properties
##
service:
  ## Service type
  ##
  type: ClusterIP

  ## HTTP Port
  ##
  port: 80

  ## HTTPS Port
  ##
  httpsPort: 443

  ## Specify the nodePort(s) value(s) for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePorts:
    http: ""
    https: ""

  ## Set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  # loadBalancerIP:

  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}

  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster

## Ingress paramaters
##
ingress:
  ## Set to true to enable ingress record generation
  ##
  enabled: true

  ## Set this to true in order to add the corresponding annotations for cert-manager
  ##
  certManager: true

  ## When the ingress is enabled, a host pointing to this will be created
  ##
  hostname: nginx-test-ecr-sanity-3-mod.dev.run.rafay-edge.net

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations: {}
  #  kubernetes.io/ingress.class: nginx
  rafaygslb: true
  ## The list of additional hostnames to be covered with this ingress record.
  ## Most likely the hostname above will be enough, but in the event more hosts are needed, this is an array
  ## hosts:
  ## - name: example.local
  ##   path: /

  ## The tls configuration for the ingress
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  ##
  tls:
    - hosts:
        - nginx-test-ecr-sanity-3-mod.run.rafay-edge.net
      secretName: nginx-ingress-secrets-dev

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  #   - name: nginx-webserver-secrets-tls
  #   - certificate: -----BEGIN CERTIFICATE----- MIIFYTCCBEmgAwIBAgISA+YGI1CWfLnciTda714nrgWvMA0GCSqGSIb3DQEBCwUA MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDAzMjEwNTA1MzFaFw0y MDA2MTkwNTA1MzFaMB8xHTAbBgNVBAMMFCouZGV2LnJhZmF5LWVkZ2UubmV0MIIB IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsubUL3UoutQ8977/wEyxZm/H 4M2CDjaYuUwlsya+cjjMMTyiRLZOyaCpqKmtxOYHTLgLjqsK+NdDAho6MnOt6BIe zEVyEddeGNos/dgLTQJuKB8ChnTNmno5iMaZBz4pveZE/ccrmLIOX+B5dfg9DS90 FbXVpRdoaiRasSnynX0fq7Ak2FV0sA7X9qCED4u2oGx9e+qS7SNKE5rHcpeTiqzY /Ubsjqa4fcVekwlB49nvC4Sb4EnSQrWMu+5cUyN3W7POBpNSEkCvq8WqPEheNp9p oKcJ8ROSCV4dcO8clmyGZzxRWRFJzq4xknWkNzWaq7AqNMqwlBUhXo++FVdm+wID AQABo4ICajCCAmYwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMB BggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSCTdDNEJVFRTiU1D47 KGiRkZU96jAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEF BQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5j cnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5j cnlwdC5vcmcvMB8GA1UdEQQYMBaCFCouZGV2LnJhZmF5LWVkZ2UubmV0MEwGA1Ud IARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0 dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDx AHcAsh4FzIuizYogTodm+Su5iiUgZ2va+nDnsklTLe+LkF4AAAFw+7JNBAAABAMA SDBGAiEAyqKF3jF83FXVOhzh+gXm99djsVrhmqr50hp5su0wAbcCIQCOp1cNZag5 EyE8vGrfl2uoy0has8s7/VAU6cKsKklUkwB2AOcS8rA3fhpi+47JDGGE8ep7N8tW HREmW/Pg80vyQVRuAAABcPuyTQ4AAAQDAEcwRQIgEVdbl39VEIMpWpVFJFUvO4on 7jXEvHvMBrOKVaHs8hMCIQChRuVugQkGizt8X5CMGrxIeL066NFbjBFk+rl7vLjI fDANBgkqhkiG9w0BAQsFAAOCAQEAOuuhzrElob2+StgQJkLt/CwwmNy97bqIC5kC sc2+bI+tK3PU3DpmHBZHHHPRcYiQrsg+k/MIN1HfL5gp5k0NYgzwoUNnP3tuhjoB /w6UQxCwDu8lJpVWZA2GZapjXZYbYXTJ0FTPr6RPgVFR3cgv92HTrMfRhSMhoq3f uq44LwD2bVG+yWXaKqN4nI0Lm2eSpFH7z38j1GV4I0g93XTTPDZHD3b7QxLiH1Z9 Yc1zX79fbIOVLcE1YnaVWOnp7X4nJwp+WyUcBXQsc+n4jff1Eni14IKQAEs+8URM t0BpmjZjrAthI8OQorMPaBp1b0zxjtqXngHQ3Gn32DOCirD++w== -----END CERTIFICATE----- -----BEGIN CERTIFICATE----- MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/ MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8 SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0 Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/ wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6 KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg== -----END CERTIFICATE-----
  #   - key: -----BEGIN PRIVATE KEY----- MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCy5tQvdSi61Dz3 vv/ATLFmb8fgzYIONpi5TCWzJr5yOMwxPKJEtk7JoKmoqa3E5gdMuAuOqwr410MC Gjoyc63oEh7MRXIR114Y2iz92AtNAm4oHwKGdM2aejmIxpkHPim95kT9xyuYsg5f 4Hl1+D0NL3QVtdWlF2hqJFqxKfKdfR+rsCTYVXSwDtf2oIQPi7agbH176pLtI0oT msdyl5OKrNj9RuyOprh9xV6TCUHj2e8LhJvgSdJCtYy77lxTI3dbs84Gk1ISQK+r xao8SF42n2mgpwnxE5IJXh1w7xyWbIZnPFFZEUnOrjGSdaQ3NZqrsCo0yrCUFSFe j74VV2b7AgMBAAECggEAexJ69C74Fxb83j6COKtJ+zt42Ljn+JkslYTCBq3npDJY nqKkyvpT1zd0n7gi9+p7KRcPtFUMlkWYLnEWijC0eYtFrqczovxzGku1WefvVkoO uAElPpRKATSGMgbVrXrhQmeQHLmQz1nms6R8SmC8tz5m8KyHziv9Q8/AqFJAOoB6 1UGF+qoJ0OyyL2nDzeexH+Y/YhOOfigOrU+2JZ25N0MlV+vHJ6xse25zwHajB29D 6IDUP9Np8tPOHes0zgvoN/9SRB9VZknu7whrugPscMjK7Ed/a53mZIL2z+jU/9a9 /mTuuNKZbXitMzrWwFg6DA8mkJaI+YvVxFN4MpEISQKBgQDp50uYdWxyKLSCM8CY HBAwUtCvZl7selC8dRseiRHK7UP4P+VE0FQP5dV329DHzHXcOa6Lj7Q9sezXQ50U iPESCnk+vxDtzPvNzMYXQvBl53lhaxnHWjN4NDDh2AqJnqOWsuAV1Q8nFj4qYybh TkZM75q8VaFQadFC2DVhmRrr9wKBgQDDzV+kIC4pWEieVsHPJFiR1nv7pNcJMvfp KQ+JRBQkT8aZJLe5c3nJMVJcC0ibFMKf1R6hzu5XuQD8RzvOo5wU+MnNHKzw3TKj GWP7gaq+XvAumU2qmHsBv9GwB1i1yFhm2rYFR3ukJ18NXmzCW6r54MIB+4AyfsNQ V7ptWWe0HQKBgQDLEEJQ2aCMe0o6vzM02ygyy7Lgk79VDduJwSEKIXWQ9utLWi1w 0GwqYR4yMGPREXBBANLH1rpj1VQIjmqQqVKglvcrwjSwPoVc5aoUB8ksrwhxyslW iLimYqkNaMG9ODxNWH2ydoXxKR5PLkVS1OGzaVCssKqbZUKHBa1STdlRgQKBgH8u gmYwROu0HY9D2SW8fQ9VmzjsbITcJ226rw3BO7gOXXiSAgiiukN2FwIUjje1d2ms W/ZMXEJ8t+gmOPHTEgoJQ8NIUgkuFLsePfRa2FZJgocyKuGZo6SSPRiy3OtO1CUT AVJSiTwqGrKrV8ezFU6zsDDrdOzXq/Qe18g5X4P9AoGBANGqHvQJlXJ9HJ3OSTSf QgrNP9YTGwvFPzoCB2fwP6fYHbRdd14oUUEQahzqRuwAwNGrU8Rihf4dvaTOlDT/ QfX8YqOJDktOHJ/f8jsXN7McivRKGirFsLjp/Ksu8co/kSH15MMDUY3TU7Yvke+E PRysb32TIe9A2WX2sCqD5AZf -----END PRIVATE KEY-----
## Prometheus Exporter / Metrics
##
metrics:
  enabled: false

  ## Bitnami NGINX Prometheus Exporter image
  ## ref: https://hub.docker.com/r/bitnami/nginx-exporter/tags/
  ##
  image:
    registry: docker.io
    repository: bitnami/nginx-exporter
    tag: 0.5.0-debian-10-r0
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

  ## Prometheus exporter pods' annotation and labels
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"

  ## Prometheus exporter service parameters
  ##
  service:
    ## NGINX Prometheus exporter port
    ##
    port: 9113
    ## Annotations for the Prometheus exporter service
    ##
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"

  ## NGINX Prometheus exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits: {}
    #   cpu: 100m
    #   memory: 128Mi
    requests: {}
    #   cpu: 100m
    #   memory: 128Mi

  ## Prometheus Operator ServiceMonitor configuration
  ##
  serviceMonitor:
    enabled: false
    ## Namespace in which Prometheus is running
    ##
    # namespace: monitoring

    ## Interval at which metrics should be scraped.
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    # interval: 10s

    ## Timeout after which the scrape is ended
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    # scrapeTimeout: 10s

    ## ServiceMonitor selector labels
    ## ref: https://github.com/bitnami/charts/tree/master/bitnami/prometheus-operator#prometheus-configuration
    ##